# This workflow will build a .NET project for deployment and store the commit that triggered it via an artifact

name: Build

on:
  workflow_dispatch:
#  push:
#    branches:
#      - deployment-automation # will be main when action is out of testing phase

env:
  BUILD_COMMIT: 'last-build-version'
  SOLUTION_PATH: './MESS/MESS.sln'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release

      - name: Publish
        run: dotnet publish ${{ env.SOLUTION_PATH }} -c Release -o ${{ env.DOTNET_ROOT }}/myapp

      - name: Record commit SHA
        run: echo "${{ github.sha }}" > ${{ env.DOTNET_ROOT }}/myapp/${{ env.BUILD_COMMIT }}.txt

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_COMMIT }}
          path: ${{ env.DOTNET_ROOT }}/myapp/${{ env.BUILD_COMMIT }}.txt
