name: Deploy

on:
  #schedule:
  #  - cron: '0 0 * * *'  # midnight UTC (NOTE: convert UTC to EST for local timezone)
  workflow_dispatch:

env:
  BUILD_COMMIT: 'last-build-version'
  LAST_DEPLOY_COMMIT: 'last-deploy-version'
  DEPLOY_STATE_ARTIFACT: 'deployed-version'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

#      Steps do upload the initial version number artifact
#      - name: Record commit SHA
#        run: echo "${{ github.sha }}" > VERSION.txt

#      - name: Archive
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ env.LAST_DEPLOY_COMMIT }}
#          path: VERSION.txt

#       Steps to read last deployed artifact 
      - name: Get run ID of last Deploy workflow
        id: get-prev-run-id  
        run: |
          OTHER_REPO="${{ github.repository }}"
          WF_NAME="Deploy"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[1].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Download last artifact from this workflow
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LAST_DEPLOY_COMMIT }}
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-prev-run-id.outputs.run-id }}

      - name: Archive old version number (in case job doesn't finish)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LAST_DEPLOY_COMMIT }}
          path: ${{ env.LAST_DEPLOY_COMMIT }}.txt

      - name: Read last deployed SHA (if exists)
        id: last-version
        run: |
          if [ -f ${{ env.LAST_DEPLOY_COMMIT }}.txt ]; then
            echo "sha=$(cat ${{ env.LAST_DEPLOY_COMMIT }}.txt)" >> $GITHUB_OUTPUT
          else
            echo "sha=" >> $GITHUB_OUTPUT
          fi

#       Steps to download Build artifact 
      - name: Get run ID of Build workflow
        id: get-run-id  
        run: |
          OTHER_REPO="${{ github.repository }}"
          WF_NAME="Build"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
          echo "Detected latest run id of ${RUN_ID} for workflow ${WF_NAME}"
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Download artifact from "Build .Net Project" workflow
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_COMMIT }}
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          run-id: ${{ steps.get-run-id.outputs.run-id }}

      - name: Read built commit SHA
        id: built-version
        run: |
          echo "sha=$(cat ${{ env.BUILD_COMMIT }}.txt)" >> $GITHUB_OUTPUT

      - name: Compare SHAs
        id: compare
        run: |
          if [ "${{ steps.built-version.outputs.sha }}" == "${{ steps.last-version.outputs.sha }}" ]; then
            echo "No new build to deploy."
            echo "deploy=false" >> $GITHUB_OUTPUT
          else
            echo "New build detected!"
            echo "deploy=true" >> $GITHUB_OUTPUT
          fi
#          ls                                       lists downloaded artifacts
#          cat ${{ env.LAST_DEPLOY_COMMIT }}.txt    display slast deploy commit artifact
#          cat ${{ env.BUILD_COMMIT }}.txt          displays last build commit artifact

      - name: Re-upload old version number if no new build
        if: steps.compare.outputs.deploy == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LAST_DEPLOY_COMMIT }}
          path: ${{ env.LAST_DEPLOY_COMMIT }}.txt

      - name: Exit if no new build
        if: steps.compare.outputs.deploy == 'false'
        run: exit 0

#      DO PUBLISH TO AZURE THINGS HERE

      - name: Record build SHA into last deployed sha 
        run: echo "$(cat ${{ env.BUILD_COMMIT }}.txt)" > ${{ env.LAST_DEPLOY_COMMIT }}.txt

      - name: Archive New version number
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LAST_DEPLOY_COMMIT }}
          path: ${{ env.LAST_DEPLOY_COMMIT }}.txt